buildscript.run = false

# Build script compiles gdbjit.c; we do it as a cxx_library instead.
[[cxx_library]]
name = "gdbjit-helpers"
srcs = ["gdbjit.c"]
compiler_flags = ["-DVERSIONED_SUFFIX=_42_0_1"]
