[workspace]

[package]
name = "rust-third-party"
version = "0.0.0"
publish = false
edition = "2024"

# Dummy target to keep Cargo happy
[[bin]]
name = "fake"
path = "/dev/null"

[dependencies]
anyhow = "1"
regex = "1"
wit-bindgen = "0.46"
wasmtime = "41"
wasmtime-wasi = { version = "41", default-features = false, features = ["p2"] }
